# Generated by Django 6.0 on 2026-01-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], default='PAYMENT', max_length=10)),
                ('session_url', models.URLField(help_text='URL to Stripe payment session', max_length=500)),
                ('session_id', models.CharField(help_text='Stripe payment session ID', max_length=255)),
                ('money_to_pay', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowings.borrowing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
